<?php
/**
 * @file
 *   A page module that provides database tables and a frontend for kapi-manager
 */


/**
 * Implements hook_permission().
 */
function kapi_manager_permission() {
  return array(
    'access kapi_manager content' => array(
      'title' => t('Access content for the Kapi-Manager module.'),
    ),
    'administrate kapi_manager content' => array(
      'title' => t('Administrate content for the Kapi-Manager module.'),
      'restrict access' => TRUE,
    ),
  );
}

/*
 * Implements hook_menu().
 */
function kapi_manager_menu() {
  module_load_include('inc', 'kapi_manager', 'admin/menu');
  $items = array();
  // TODO: switch admin permission after development/testing
//  $admin_access = array('access kapi_manager administrate');
  $admin_access = array('access kapi_manager content');
  $user_access = array('access kapi_manager content');

  kapi_manager_admin_menu($items, $admin_access);

  return $items;
}

function kapi_manager_test_page() {
  return t('Hello! This is a test page.');
}

/**
 * This function generates a page containing the workshop list.
 */
function kapi_manager_list_workshops_page() {
  drupal_set_title(t('Workshop'));
  module_load_include('inc', 'kapi_manager', 'database/workshop_handler');
  $result = _kapi_manager_get_workshops();
  $rows = array();
  foreach ($result as $workshop) {
    $rows[] = array(
      array('data' => $workshop->name, ),
      array('data' => l('edit', "kapi_manager/admin/workshop/$workshop->id/edit"), ),
      array('data' => l('delete', "kapi_manager/admin/workshop/$workshop->id/edit"), ),
    );
  }
  $header = array(
		  array('data' => 'Name', 'align' => 'center', ),
    array('data' => 'Operations', 'align' => 'center', 'colspan' => 2, ),
  );
  return theme('table', array('header' => $header, 'rows' => $rows));
}

function kapi_manager_edit_workshop_page($workshop_id) {
	return t("TODO: implement edit workshop page (workshop_id: '@workshop_id')", array('@workshop_id' => $workshop_id));
}

/**
 * This function generates a page containing the product list.
 */
function kapi_manager_list_products_page() {
  drupal_set_title(t('Product'));
  module_load_include('inc', 'kapi_manager', 'database/product_handler');
  $result = _kapi_manager_get_products();
  $rows = array();
  foreach ($result as $product) {
    $rows[] = array(
      array('data' => $product->id, ),
      array('data' => $product->name, ),
    );
  }
  $header = array(
    array('data' => 'id', 'align' => 'center'),
    array('data' => 'name', 'align' => 'center'),
  );
  return theme('table', array('header' => $header, 'rows' => $rows));
}

/**
 * wrapper to call private form function in 'admin/forms/workshops.inc'.
 */
function kapi_manager_add_workshop_form($form, &$form_state, $workshop_id) {
  module_load_include('inc', 'kapi_manager', 'admin/forms/workshops');
  return _kapi_manager_add_workshop_form($form, $form_state, $workshop_id);
}

/**
 * wrapper to call private form validate function in 'admin/forms/workshops.inc'.
 */
function kapi_manager_add_workshop_form_validate($form, &$form_state) {
  module_load_include('inc', 'kapi_manager', 'admin/forms/workshops');
  return _kapi_manager_add_workshop_form_validate($form, $form_state);
}

/**
 * wrapper to call private form submit function in 'admin/forms/workshops.inc'.
 */
function kapi_manager_add_workshop_form_submit($form, &$form_state) {
  module_load_include('inc', 'kapi_manager', 'admin/forms/workshops');
  return _kapi_manager_add_workshop_form_submit($form, $form_state);
}

/**
 * wrapper to call private form function in 'admin/forms/products.inc'.
 */
function kapi_manager_add_product_form($node, &$form_state) {
  module_load_include('inc', 'kapi_manager', 'admin/forms/products');
  return _kapi_manager_add_product_form($node, $form_state);
}

/**
 * wrapper to call private form validate function in 'admin/forms/products.inc'.
 */
function kapi_manager_add_product_form_validate($form, &$form_state) {
  module_load_include('inc', 'kapi_manager', 'admin/forms/products');
  return _kapi_manager_add_product_form_validate($form, $form_state);
}

/**
 * wrapper to call private form submit function in 'admin/forms/products.inc'.
 */
function kapi_manager_add_product_form_submit($form, &$form_state) {
  module_load_include('inc', 'kapi_manager', 'admin/forms/products');
  return _kapi_manager_add_product_form_submit($form, $form_state);
}
